name: gender_hack
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  csv: ^6.0.0
  df: ^0.4.0-nullsafety.0
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^2.5.2
  lottie: ^3.3.2
  multiselect_field: ^1.6.8
  persistent_bottom_nav_bar: ^6.2.1
  stylish_bottom_bar: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/story/
    - assets/data/
